apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich

images:
- name: ghcr.io/immich-app/immich-machine-learning
  newTag: v1.131.2 
- name: ghcr.io/immich-app/immich-server
  newTag: v1.133.0 
